from django.urls import path, include
from django.contrib.auth.decorators import login_required, user_passes_test
from . import views

# Vérifie si l'utilisateur est un administrateur
def admin_required(user):
    return user.is_authenticated and user.is_staff

# Applique le décorateur admin_required à toutes les vues du dashboard admin
admin_patterns = [
    path('', views.dashboard_home, name='admin_home'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('biens/', views.BienImmobilierListView.as_view(), name='bien_list'),
]

urlpatterns = [
    # Tableau de bord d'administration personnalisé
    path('admin/', include((admin_patterns, 'admin_dashboard'), namespace='admin_dashboard')),
    
    # Anciennes vues (à supprimer progressivement)
    path('', views.home, name='home'),
    path('analytics-variation/', views.analytics_variation, name='analytics_variation'),
    path('apps-chat/', views.apps_chat, name='apps_chat'),
    path('apps-faq-section/', views.apps_faq_section, name='apps_faq_section'),
    path('apps-forum-discussion/', views.apps_forum_discussion, name='apps_forum_discussion'),
    path('apps-forum-list/', views.apps_forum_list, name='apps_forum_list'),
    path('apps-forum-threads/', views.apps_forum_threads, name='apps_forum_threads'),
    path('apps-mailbox/', views.apps_mailbox, name='apps_mailbox'),
    path('charts-apexchart/', views.charts_apexchart, name='charts_apexchart'),
    path('charts-chartjs/', views.charts_chartjs, name='charts_chartjs'),
    path('charts-sparklines/', views.charts_sparklines, name='charts_sparklines'),
    path('components-accordions/', views.components_accordions, name='components_accordions'),
    path('components-calendar/', views.components_calendar, name='components_calendar'),
    path('components-carousel/', views.components_carousel, name='components_carousel'),
    path('components-count-up/', views.components_count_up, name='components_count_up'),
    path('components-guided-tours/', views.components_guided_tours, name='components_guided_tours'),
    path('components-image-crop/', views.components_image_crop, name='components_image_crop'),
    path('components-loading-blocks/', views.components_loading_blocks, name='components_loading_blocks'),
    path('components-maps/', views.components_maps, name='components_maps'),
    path('components-modals/', views.components_modals, name='components_modals'),
    path('components-notifications/', views.components_notifications, name='components_notifications'),
    path('components-pagination/', views.components_pagination, name='components_pagination'),
    path('components-progress-bar/', views.components_progress_bar, name='components_progress_bar'),
    path('components-rating/', views.components_rating, name='components_rating'),
    path('components-scrollable-elements/', views.components_scrollable_elements, name='components_scrollable_elements'),
    path('components-tabs/', views.components_tabs, name='components_tabs'),
    path('components-tooltips-popovers/', views.components_tooltips_popovers, name='components_tooltips_popovers'),
    path('components-tree-view/', views.components_tree_view, name='components_tree_view'),
    path('dashbords-commerce-variation/', views.dashbords_commerce_variation, name='dashbords_commerce_variation'),
    path('dashbords-commerce/', views.dashbords_commerce, name='dashbords_commerce'),
    path('dashbords-crm-variation/', views.dashbords_crm_variation, name='dashbords_crm_variation'),
    path('dashbords-crm/', views.dashbords_crm, name='dashbords_crm'),
    path('dashbords-minimal-1/', views.dashbords_minimal_1, name='dashbords_minimal_1'),
    path('dashbords-minimal-2/', views.dashbords_minimal_2, name='dashbords_minimal_2'),
    path('dashbords-sales/', views.dashbords_sales, name='dashbords_sales'),
    path('dashbords-babges-labels/', views.dashbords_babges_labels, name='dashbords_babges_labels'),
    path('elements-badges-labels/', views.elements_badges_labels, name='elements_badges_labels'),
    path('elements-buttons-icons/', views.elements_buttons_icons, name='elements_buttons_icons'),
    path('elements-buttons-pills/', views.elements_buttons_pills, name='elements_buttons_pills'),
    path('elements-buttons-shadow/', views.elements_buttons_shadow, name='elements_buttons_shadow'),
    path('elements-buttons-square/', views.elements_buttons_square, name='elements_buttons_square'),
    path('elements-standard/', views.elements_standard, name='elements_standard'),
    path('elements-crads/', views.elements_crads, name='elements_crads'),
    path('elements-dropdowns/', views.elements_dropdowns, name='elements_dropdowns'),
    path('elements-icons/', views.elements_icons, name='elements_icons'),
    path('elements-list-group/', views.elements_list_group, name='elements_list_group'),
    path('elements-loaders/', views.elements_loaders, name='elements_loaders'),
    path('elements-navigation/', views.elements_navigation, name='elements_navigation'),
    path('elements-timelines/', views.elements_timelines, name='elements_timelines'),
    path('elements-utilities/', views.elements_utilities, name='elements_utilities'),
    path('forms-clipboard/', views.forms_clipboard, name='forms_clipboard'),
    path('forms-controls/', views.forms_controls, name='forms_controls'),
    path('forms-datepicker/', views.forms_datepicker, name='forms_datepicker'),
    path('forms-input-masks/', views.forms_input_masks, name='forms_input_masks'),
    path('forms-input-selects/', views.forms_input_selects, name='forms_input_selects'),
    path('forms-layouts/', views.forms_layouts, name='forms_layouts'),
    path('forms-range-slider/', views.forms_range_slider, name='forms_range_slider'),
    path('forms-textarea-autosize/', views.forms_textarea_autosize, name='forms_textarea_autosize'),
    path('forms-toggle-switch/', views.forms_toggle_switch, name='forms_toggle_switch'),
    path('forms-validation/', views.forms_validation, name='forms_validation'),
    path('forms-wizard/', views.forms_wizard, name='forms_wizard'),
    path('forms-wysiwyg-editor/', views.forms_wysiwyg_editor, name='forms_wysiwyg_editor'),
    path('pages-forgot-password/', views.pages_forgot_password, name='pages_forgot_password'),
    path('pages-forgot-password-boxed/', views.pages_forgot_password_boxed, name='pages_forgot_password_boxed'),
    path('pages-login-boxed/', views.pages_login_boxed, name='pages_login_boxed'),
    path('pages-login/', views.pages_login, name='pages_login'),
    path('pages-register-boxed/', views.pages_register_boxed, name='pages_register_boxed'),
    path('pages-register/', views.pages_register, name='pages_register'),
    path('tables-data-tables/', views.tables_data_tables, name='tables_data_tables'),
    path('tables-grid/', views.tables_grid, name='tables_grid'),
    path('tables-regular/', views.tables_regular, name='tables_regular'),
    path('widgets-chart-boxes-2/', views.widgets_chart_boxes_2, name='widgets_chart_boxes_2'),
    path('widgets-chart-boxes-3/', views.widgets_chart_boxes_3, name='widgets_chart_boxes_3'),
    path('widgets-profile-boxes/', views.widgets_profile_boxes, name='widgets_profile_boxes'),
]