# Generated by Django 5.2.3 on 2025-07-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS comptes_maison;
            DROP TABLE IF EXISTS comptes_appartement;
            DROP TABLE IF EXISTS comptes_terrain;
            DROP TABLE IF EXISTS comptes_bienimmobilier;
            """,
            reverse_sql="""
            -- Reverse operations will be handled by Django when creating tables
            """
        ),
    ]
