# Generated by Django 5.2.3 on 2025-07-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_auto_20250714_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('Maison', 'Maison'), ('Appartement', 'Appartement'), ('Terrain', 'Terrain')], max_length=20)),
                ('superficie', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='biens/')),
            ],
            options={
                'db_table': 'comptes_bienimmobilier',
            },
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_chambre', models.IntegerField(blank=True, null=True)),
                ('piece_speciale', models.CharField(blank=True, max_length=255, null=True)),
                ('nbr_etages', models.IntegerField(blank=True, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maison', to='comptes.bienimmobilier')),
            ],
            options={
                'db_table': 'comptes_maison',
            },
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etage', models.IntegerField(blank=True, null=True)),
                ('nbr_chambre', models.IntegerField(blank=True, null=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appartement', to='comptes.bienimmobilier')),
            ],
            options={
                'db_table': 'comptes_appartement',
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_parcelles', models.IntegerField()),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terrain', to='comptes.bienimmobilier')),
            ],
            options={
                'db_table': 'comptes_terrain',
            },
        ),
    ]
