# Generated by Django 5.2.1 on 2025-07-25 23:28

import comptes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienimmobilier',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du bien (max 2000 caractères)', max_length=2000),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du bien (JPG, PNG, WEBP, max 10MB)', null=True, upload_to='biens/', validators=[comptes.utils.validate_file_size, comptes.utils.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Prix en euros', max_digits=10, validators=[comptes.utils.validate_prix]),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='superficie',
            field=models.FloatField(help_text='Superficie en m²', validators=[comptes.utils.validate_superficie]),
        ),
    ]
