# Generated by Django 5.2.3 on 2025-07-14 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_auto_20250714_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'profession': 'proprietaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='bienimmobilier',
            table=None,
        ),
    ]
