# Generated by Django 4.2.23 on 2025-07-17 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_bienimmobilier_proprietaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('remarques', models.TextField(blank=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.bienimmobilier')),
                ('client', models.ForeignKey(limit_choices_to={'profession': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
