# Generated by Django 5.2.4 on 2025-07-27 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_bienimmobilier_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bienimmobilier',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
    ]
