# Generated by Django 5.2.1 on 2025-07-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_update_proprietaire'),
        ('comptes', '0005_visite'),
    ]

    operations = [
    ]
