# Generated by Django 5.2.1 on 2025-07-21 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_add_description_to_annonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='document',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='annonce',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type_annonce',
            field=models.CharField(choices=[('location', 'Location'), ('vente', 'Vente')], default='vente', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paiement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='visite',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visite',
            name='proprietaire',
            field=models.ForeignKey(blank=True, limit_choices_to={'profession': 'proprietaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visites_proprietaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text='Chaque bien doit avoir un propriétaire.', limit_choices_to={'profession': 'proprietaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visite',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='comptes.bienimmobilier'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='client',
            field=models.ForeignKey(limit_choices_to={'profession': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='visites_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visite',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée'), ('confirme', 'Confirmée')], default='planifiee', max_length=20),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
