# Generated by Django 5.2.1 on 2025-07-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_remove_paiement_date_paiement_and_more'),
    ]

    operations = [
    ]
